### ISSUE TITLE
Spawn prevention failing at random

### ISSUE THREAD

**Issue by ghost** [yarrim/MobInhibitor#3] opened 2016-01-07 04:09 UTC
I've been playing around with these for a couple of days now with mixed results.

Spawn prevention seems to outright fail on chunk unload, requiring me to reset the block by breaking it and replacing it. 

I'm not sure if you're actively maintaining this but, I hope you are. This is currently the only mod I can find that prevents passive mobs from spawning. It's been a game changer for building in void dimensions such as The Last Millennium. 

I'll frequently return to my void world only to find my tunnels full of bats. Any insight as to what might be happening here? Chunkloading is always an option though, I'd prefer not to load over a hundred chunks if I can help it. 

Edit: Upon further testing, mob inhibitors appear to fail after a set period of time. I'm not at all sure what's happening here but, they don't appear to be working properly at all. I came back to cows, sheep, pigs and, horses everywhere. I hadn't unloaded the area. I was standing there as it happened.

Edit 2: After some additional testing, I'm beginning to think I wandered just a little bit to far thus unloading the chunk. I'm leaning back towards this being a chunkloading issue. I'll be loading chunks as a test, though loading over 100 chunks isn't optimal.

**Comment by yarrim** [comment] 2016-01-07 13:01
I guess I'm actively maintaining this. I've had a request to port it to 1.8 and apparently missed something when reloading a chunk. I'm working to get a development workspace back up and running, and will take a look.

**Comment by ghost** [comment] 2016-01-07 13:33
Many thanks. Without m.f.f.s passive spawn prevention is pretty much impossible.

**Comment by yarrim** [comment] 2016-01-08 01:32
I've added some pretty verbose logging to my workspace and I found at least one of the problems: When unloading a World, I cleared the list of inhibitors, erroneously thinking the world unload was akin to the server shutting down. It is not; it is only a dimension unload. This means someone leaving a dimension like the nether, with no other players in it will clobber the list of inhibitors for other dimensions, even if chunk loaded.

 Additionally, it means that inhibitors have cross-dimension effects... something I hadn't considered.

I have tested some cases of loading/unloading inhibitors without crossing dimensions and they seem to work as expected. I _think_ the problem you are seeing is caused by your movement into your void dimension unloading the overword(or whatever) and clearing all active inhibitors.

I'll be building a slightly less verbose logging .jar and playing with it to see if things behave. Stay tuned.

**Comment by yarrim** [comment] 2016-01-09 01:01
I've released mobinhibitors-1.7.10-1.1 which, I believe, fixes this problem. I'm going to close this issue, because I don't think github has a 'probably fixed' status. If you update and continue to experience bats in your caves, please open a new issue.

**Closed as completed by yarrim** 2016-01-09 01:01 UTC

**Comment by ghost** [comment] 2016-01-09 08:20
Thanks, will be pushing this out to my server for testing. I'll let you know if any issues arise.
